timezone: America/Chicago
# Jobs checked every minute.
interval: 10
discordConnector: false
jobs:
  #Restart the server every morning @ ~4am.
  #  #Alert players.
  - command: broadcast center <color=red>Warning - Reserver Restart in 5 Minutes!</color>
    schedule: "55 3 * * *"
  - command: say Warning - Reserver Restart in 5 Minutes!
    schedule: "55 3 * * *"
  - command: broadcast center <color=red>Warning - Reserver Restart in 4 Minutes!</color>
    schedule: "56 3 * * *"
  - command: say Warning - Reserver Restart in 4 Minutes!
    schedule: "56 3 * * *"
  - command: broadcast center <color=red>Warning - Reserver Restart in 3 Minutes!</color>
    schedule: "57 3 * * *"
  - command: say Warning - Reserver Restart in 3 Minutes!
    schedule: "57 3 * * *"
  - command: broadcast center <color=red>Warning - Reserver Restart in 2 Minutes!</color>
    schedule: "58 3 * * *"
  - command: say Warning - Reserver Restart in 2 Minutes!
    schedule: "58 3 * * *"
  - command: broadcast center <color=red>Warning - Reserver Restart in 1 Minutes!</color>
    schedule: "59 3 * * *"
  - command: say Warning - Reserver Restart in 1 Minutes!
    schedule: "59 3 * * *"
  - command: save
    schedule: "59 3 * * *"

  #Refresh Chests every 10 days.
  #Alert players.
  - command: broadcast center <color=orange>Notice - ♻ Chest Refill Beginning ♻</color>
    schedule: "0 5 */10 * 1"
  - command: say Notice - ♻ Chest Refill Beginning ♻
    schedule: "0 5 */10 * 1"
  - command: chests_reset TreasureChest_meadows looted
    schedule: "1 5 */10 * *"
  - command: chests_reset TreasureChest_meadows_buried looted
    schedule: "2 5 */10 * *"
  - command: chests_reset TreasureChest_blackforest looted
    schedule: "3 5 */10 * *"
  - command: chests_reset TreasureChest_fCrypt looted
    schedule: "4 5 */10 * *"
  - command: chests_reset TreasureChest_forestcrypt looted
    schedule: "5 5 */10 * *"
  - command: chests_reset TreasureChest_forestcrypt_hildir looted
    schedule: "6 5 */10 * *"
  - command: chests_reset TreasureChest_trollcave looted
    schedule: "7 5 */10 * *"
  - command: chests_reset shipwreck_karve_chest looted
    schedule: "8 5 */10 * *"
  - command: chests_reset TreasureChest_sunkencrypt looted
    schedule: "9 5 */10 * *"
  - command: chests_reset TreasureChest_swamp looted
    schedule: "10 5 */10 * *"
  - command: chests_reset TreasureChest_mountaincave looted
    schedule: "11 5 */10 * *"
  - command: chests_reset TreasureChest_mountaincave_hildir looted
    schedule: "12 5 */10 * *"
  - command: chests_reset TreasureChest_mountains looted
    schedule: "13 5 */10 * *"
  - command: chests_reset TreasureChest_heath looted
    schedule: "14 5 */10 * *"
  - command: chests_reset TreasureChest_heath_hildir looted
    schedule: "15 5 */10 * *"
  - command: chests_reset TreasureChest_plains_stone looted
    schedule: "16 5 */10 * *"
  - command: chests_reset TreasureChest_plainsfortress_hildir looted
    schedule: "17 5 */10 * *"
  - command: chests_reset TreasureChest_dvergr_loose_stone looted
    schedule: "18 5 */10 * *"
  - command: chests_reset TreasureChest_dvergrtower looted
    schedule: "19 5 */10 * *"
  - command: chests_reset TreasureChest_dvergrtown looted
    schedule: "20 5 */10 * *"
  - command: chests_reset TreasureChest_ashland_stone looted
    schedule: "21 5 */10 * *"
  - command: chests_reset TreasureChest_charredfortress looted
    schedule: "22 5 */10 * *"
  - command: broadcast center <color=orange>Notice - ♻ Chest Refill Complete ♻</color>
    schedule: "23 5 */10 * 1"
  - command: say Notice - ♻ Chest Refill Complete ♻
    schedule: "23 5 */10 * 1"

  #Recycle the world every 15 days
  #===Alert players.
  - command: broadcast center <color=red>♻ World Recycling ♻ in 5 Minutes!</color>
    schedule: "55 5 */15 * *"
  - command: say ♻ World Recycling ♻ in 5 Minutes!
    schedule: "55 5 */15 * *"
  - command: broadcast center <color=red>♻ World Recycling ♻ in 4 Minutes!</color>
    schedule: "56 5 */15 * *"
  - command: say ♻ World Recycling ♻ in 4 Minutes!
    schedule: "56 5 */15 * *"
  - command: broadcast center <color=red>♻ World Recycling ♻ in 3 Minutes!</color>
    schedule: "57 5 */15 * *"
  - command: say ♻ World Recycling ♻ in 3 Minutes!
    schedule: "57 5 */15 * *"
  - command: broadcast center <color=red>♻ World Recycling ♻ in 2 Minutes!</color>
    schedule: "58 5 */15 * *"
  - command: say ♻ World Recycling ♻ in 2 Minutes!
    schedule: "58 5 */15 * *"
  - command: broadcast center <color=red>♻ World Recycling ♻ in 1 Minutes!</color>
    schedule: "59 5 */15 * *"
  - command: say ♻ World Recycling ♻ in 1 Minutes!
    schedule: "59 5 */15 * *"
  - command: backup
    schedule: "59 5 */15 * *"
  #===Meadows
  - command: say Recycling... Meadows
    schedule: "0 6 */15 * *"
  - command: zones_reset safeZones=4 biomes=Meadows start
    schedule: "0 6 */15 * *"
  #===BlackForest
  - command: say Recycling... Black Forest
    schedule: "1 6 */15 * *"
  - command: zones_reset safeZones=4 biomes=BlackForest start
    schedule: "1 6 */15 * *"
  #===Ocean
  - command: say Recycling... Oceans
    schedule: "2 6 */15 * *"
  - command: zones_reset safeZones=4 biomes=Ocean start
    schedule: "2 6 */15 * *"
  #===Swamp
  - command: say Recycling... Swamps
    schedule: "3 6 */15 * *"
  - command: zones_reset safeZones=4 biomes=Swamp start
    schedule: "3 6 */15 * *"
  #===Mountain
  - command: say Recycling... Mountains
    schedule: "4 6 */15 * *"
  - command: zones_reset safeZones=4 biomes=Mountain start
    schedule: "4 6 */15 * *"
  #===Plains
  - command: say Recycling... Plains
    schedule: "5 6 */15 * *"
  - command: zones_reset safeZones=4 biomes=Plains start
    schedule: "5 6 */15 * *"
  #===Mistlands
  - command: say Recycling... Mistlands
    schedule: "6 6 */15 * *"
  - command: zones_reset safeZones=4 biomes=Mistlands start
    schedule: "6 6 */15 * *"
  #===Ashlands
  - command: say Recycling... Ashlands
    schedule: "7 6 */15 * *"
  - command: zones_reset safeZones=4 biomes=Ashlands start
    schedule: "7 6 */15 * *"
  #Complete
  - command: broadcast center <color=green>♻ World Recycling... Complete!  ♻</color>
    schedule: "8 6 */15 * *"
  - command: say ♻ World Recycling... Complete! ♻
    schedule: "8 6 */15 * *"
zone:
  #Additional recycle to ensure ore nodes are replenished
  - command: vegetation_reset rock4_copper terrain=20 zone=<i>,<j> start
    schedule: "0 * */10 * *"
    bannedObjects: rock4_copper,Thorward
    biomes: BlackForest
  - command: vegetation_reset silvervein terrain=20 zone=<i>,<j> start
    schedule: "1 * */10 * *"
    bannedObjects: silvervein,Thorward
    biomes: Mountain
    #Additional recycle to generate new dungeons
  - command: locations_reset Crypt2,Crypt3,Crypt4,SunkenCrypt4,MountainCave02,Mistlands_DvergrTownEntrance1,Mistlands_DvergrTownEntrance2 zone=<i>,<j> start
    schedule: "0 * */15 * *"
    avoidPlayers: true
    bannedObjects: Thorward
    locations: Crypt2,Crypt3,Crypt4,SunkenCrypt4,MountainCave02,Mistlands_DvergrTownEntrance1,Mistlands_DvergrTownEntrance2
  - command: locations_reset GoblinCamp2,TarPit1,TarPit2,TarPit3 zone=<i>,<j> start
    schedule: "0 * */15 * *"
    avoidPlayers: true
    bannedObjects: Thorward
    locations: GoblinCamp2,TarPit1,TarPit2,TarPit3